# Stage 1
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Stage 2
FROM caddy:2-alpine

# 🔥 KEY FIX: copy into /etc/caddy/dist
COPY --from=builder /app/dist /etc/caddy/dist

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 3000